### ISSUE TITLE
云片轨迹

### ISSUE THREAD

**Issue by scrapyhub** [Esbiya/SliderCracker#2]
对于云片可以尝试直接写上正确的轨迹，我看你写的稍麻烦，你可以尝试直接写死轨迹。

**Comment by Esbiya** [comment]
缺口距离不同怎么写死轨迹，再说这些专门做验证码的平台应该都有学习机制，同一套轨迹算法都用不了多长时间，更别说直接写死轨迹了，另外项目放出来的所有轨迹算法仅作参考。

**Comment by scrapyhub** [comment]
我的做法是缺口可以写死，然后轨迹又可以写死，我用了一个轨迹对应的缺口测试发现是可以成功的，只不过成功率低一些，但是应该可以骗过机器学习，如果我先手动划一下得到比较多的轨迹，通过率应该会提升。轨迹本身存在一个轨迹摘要的问题。例如极验可能有上亿人体轨迹样本，但是这样真实样本并没有全部入库。也就是，当出现一个和真实人体产生的轨迹，但是是某个人历史产生的轨迹，那么这个轨迹将会直接通过。另外，对于那种不专业的滑块，轨迹基本没啥用，后面根本没有Ai模型。

**Comment by Esbiya** [comment]
你的意思我明白，项目中安居客和极验就采用了这样的做法，轨迹也是收集自网上的。但是全部用现成的轨迹至少需要几百条，反正我是没有那样的精力自己去一条条收集，写个简单的算法自动生成轨迹不是更方便吗？最后不管什么样的做法，只要有效就好。
